//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimbaTvaerfagligt {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class global : global::System.Configuration.ApplicationSettingsBase {
        
        private static global defaultInstance = ((global)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new global())));
        
        public static global Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = den1.mssql5.gear.host; Initial Catalog = projectsimba User id = pro" +
            "jectsimba; Password = Qh5u5_QiC?IR;")]
        public string connectionstring_online {
            get {
                return ((string)(this["connectionstring_online"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = DESKTOP-2QN29R2\\\\SQLEXPRESS; Initial Catalog = Simba; User id = sim" +
            "bagame; Password = simbasimba;")]
        public string connectionstring_local {
            get {
                return ((string)(this["connectionstring_local"]));
            }
        }
    }
}
